apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab
  namespace: esteira-lab

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx-lab

  template:
    metadata:
      labels:
        app: nginx-lab

    spec:
      containers:
        - name: nginx-lab
          image: nginx:1.27
          ports:
            - containerPort: 80