apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-lab
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://github.com/Paulo-procopio/Gitops-kind-lab.git
      targetRevision: main
      path: apps/nginx

    - repoURL: https://github.com/Paulo-procopio/Gitops-kind-lab.git
      targetRevision: main
      path: manifests/yamls

  destination:
    server: https://kubernetes.default.svc
    namespace: cd-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true